### ISSUE TITLE
OKR i BOD

### ISSUE THREAD

**Issue by arild-65** [Altinn/metode-kompetanse#319]
[OKR_onboarding i team.docx](https://github.com/Altinn/metode-kompetanse/files/11879538/OKR_onboarding.i.team.docx)
- [x] Workshop med lederlaget - gjennomgang lederlagets OKR - videre arbeid
- [x] Bidra på verktøystøtte OKR for hele Digdir - Workshop planlagt med Futureworks
- [x] Avholdt pilot møte med team sikkerhet
- [x] Innkalt team infra til pilot møte
- [x] Avholdt pilot møte med team infra
- [x] Oppfølging team sikkerhet
- [x] Avholdt møte med Futureworks 12.12 - integrasjon mot GitHub/annet format KPI
- [x] Møte Futureworks GitHub 19.01.23 - Espen
- [x] Oversende dokumentasjon til Futureworks ved Kim i forkant av WS Studio Frist 20.01.23
- [x] Pilot OKR for team studio sammen med Futureworks - avtalt med Kim 26.01.23
- [x] Rapportere erfaringer OKR til lederlaget 7.2.23
- [x] Workshop spissing lederlagets OKR, del 1 med Futureworks
- [x] Fysisk workshop spissing lederlagets OKR, del 2, pluss planlegging av Workshop med team studio med Futureworks
- [ ] Gjennomføre OKR Workshop team studio med Futureworks
- [ ] Pilot OKR for team autorisasjon
- [ ] Oppfølging team infra
- [x] Gå gjennom erfaringer og planlegge videre OKR arbeid
- [x] Informasjon i ledermøte 22. juni
- [x] Vedtakssak i ledermøte vedr. onboarde OKR i teamene 27/6
- [x] Starte prosess med anskaffelse
- [x] 3.aug møte med innkjøp vedr. konkurranse
- [x] Konkurranse på bistand sendes ut 8. aug
- [x] Evaluere tilbud i uke 34/35
```[tasklist]
### Tasks
```
