### ISSUE TITLE
Etablere rammeverk brukertesting

### ISSUE THREAD

**Issue by SnorreTE** [Altinn/metode-kompetanse#366]
Det er behov for å få rekruttert testpersoner til brukervennlighetstest. Det er er særlig utfordrende og ressurskrevende å rekruttere privatpersoner. Eksempelvis så har OED mål om å kjøre brukervennlighetstest en gang pr. mnd. 

```[tasklist]
### Tasks
- [ ] #400 
- [ ] #412 
- [ ] #416
- [ ] https://github.com/Altinn/metode-kompetanse/issues/418
- [ ] https://github.com/Altinn/metode-kompetanse/issues/431
- [ ] Drift av Brukerbasen 
 
```

Oppgaver. 

Få i gang brukerstøtte Leikanger med rekruttering. Vi avventer denne inntil videre.   

- [x] Grave litt mer i Innkjøpsregimet

- [x] Finne ut av budsjetter i linja kontra i prosjekter, Møte med Reidun? Noen må betale for rekrutteringen og det må settes av penger til gavekort til testpersonene. Dette må spilles inn i designgruppa.  

Huskeliste: 
Sjekke om vi kan opprette "påmeldingsskjema" i Altinn-løsningen? 

Sjekk om vi kan bruke Sosiale media til rekruttering. Design skal ha et møte med KOMM i slutten av April. Dette sjekkes da.
