### ISSUE TITLE
Føringer verktøy og informasjonskanaler

### ISSUE THREAD

**Issue by WencheFylken** [Altinn/metode-kompetanse#367]
## Forutsetninger x
- For å dele en brukerhistorie opp i håndterbare komponenter, må teamet identifisere og spesifisere oppgaver (tasklist/oppgaveliste). Oppgavelisten er detaljerte aktiviteter som må utføres for å fullføre en brukerhistorie. Oppgaver kan være fra noen få timers arbeid opp til 12. Oppgavene tildeles team medlemmer som har ekspertise til å utføre dem
- NB! En Brukerhistorie er ikke Ansett som fullført før alle underliggende oppgaver er utført 

Foreløpig oppdragsbeskrivelse:
Føringer og retningslinjer for bruke av verktøy og informasjonskanaler:
1. Hvilke prinsipper skal ligge til grunn for bruk av verktøy? 
- antall brukere, felles for flere
- økonomi
- markeds påvirkninger (support, levetids plan for verktøyet, populært etc)
- Sikkerhetsvurderinger
- personlig verktøy /spesialverktøy faglig som noen trenger

2. Hovedverktøy der vi I dag har vi flere verktøy om gjør tilnærmet det samme (eksempelvis håndtering av Kanban boards i Teams, Azure Devops og GitHub)
3.  Retningslinjer kommunikasjonskanaler - Slack, Teams, Yammer, GitHub, E-post,
 
Prioriterte oppgaver er
-      Kanban (lavt hengende frukt)
o    Standardisere på GitHub
 
Oppdraget utbroderes av Tina / Marit og sendes M&K-teamet

## Brukerhistorie
- [ ] Som leder og bruker ønsker jeg oversikt over hvilke verktøy, informasjonskanaler og kriterier for bruk slik at vi dekker/ standardiserer avdelingens verktøy behov for å oppnå en forenkling.

## Brukerhistorien består av følgende oppgaver:

- [x] Hva har vi allerede i avdeling BOD på denne oppgaven, kartlegging
- [ ] Hva har vi allerede i Digdir på denne oppgaven, ikke aktuelt å se på det nå.
- [ ] Hva har vi allerede i andre etater på denne oppgaven, ikke aktuelt å se på det nå.
- [x] Gjennomgang av verktøy/informasjonskanaler som vi har kartlagt
- [x] Beskrive kriterier for å  ta i bruk verktøy. 
- [x] Beskrive kriterier på de verktøy vi har.
- [ ] Vurdere personopplysninger og personvern utføres av jurist
- [x] Vurdere arkivverdig informasjon
- [x] Rutine for sanering av verktøy
- [x] Rutine for anskaffelse av verktøy
- [x] Rutine for support og forvaltning
- [x] Gjennomføre en interessent analyse
- [x] Intervju og møter med utvalgte
- [x] Sammenstilling
- [x] Høringsrunde
- [x] Innstilling

## Akseptanse kriterium
- [ ]  Oppgave er utført, på riktig måte og med riktig resultat

**Comment by WencheFylken** [comment]
3.5. møte med Oddhild hun utreder systemer mhp personsikkerhet og informasjonssikkerhet.
9.5.2023 Har hatt møte med KOM Jørgen angående portaler og andre verktøy.
10.5.2023 Har hatt møte med arkivet på hva som er arkiv verdi informasjon.
Vi bruker Systemoversikten og tar kontakt med Terje angående koordinering for BOD med oppdateringer av systemoversikten for BOD.
27.6.2023 Møte med (Marit, Oddhild, Tina og Arild) gjennomgang av [presentasjon. Det kom opp flere nye punkter som må behandles.Forsetter arbeidet med personvern, tilgangsstyring, kontraktsforvaltning og lisenser, utarbeidelse av sjekkliste før det oversending av behovs melding til Innkjøpslaget, oppdatering av systemoversikten.
Presentasjon føringer verktøy og informasjonsportaler.
22.8.2023 møte i team Metode og kompetanse. Vi tar et nytt møte for å gjennomgå og plasser de nye oppgavene der de hører hjemme.
1.11. 2023 Verktøy og portaler er beskrevet på Baksida.
03.01.2024 De nye oppgavene er behandlet av ledelsen og ansvaret overføres til ulike seksjoner i BOD. Arild og Wenche avholder møter for overlevering, eventuelle videre oppgaver kan bli fassilitere oppgavene. oppgaven settes til ferdigstilt.
