### ISSUE TITLE
Forbedre opplegg for onboarding - samle-issue

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/metode-kompetanse#383]
Lage en samleissue for å opprette en liste over issues vi har hatt liggende i backloggen, men som vi ser vi ikke kan se på nå. Vi blir å ta en gjennomgang av issuene på et av mandagsmøtene. Alle issues som er knyttet opp til denne issuen vil ligge i kolonnen "På vent". Nå vi skal jobbe med en av issuene blir den tatt fra listen her og lag under arbeid i boardet vårt.

Noen av sakene her vil vises som Done, men det er ikke sikkert de har blitt jobbet med så derfor ligger de fortsatt i listen her.

```[tasklist]
### Tasks
- [ ] #383
- [ ] #305 
- [ ] https://github.com/Altinn/metode-kompetanse/issues/313
- [ ] https://github.com/Altinn/metode-kompetanse/issues/316
- [ ] https://github.com/Altinn/metode-kompetanse/issues/237
- [ ] https://github.com/Altinn/metode-kompetanse/issues/322
- [ ] https://github.com/Altinn/metode-kompetanse/issues/327
- [ ] https://github.com/Altinn/metode-kompetanse/issues/336
- [ ] https://github.com/Altinn/metode-kompetanse/issues/335
- [ ] https://github.com/Altinn/metode-kompetanse/issues/334
- [ ] https://github.com/Altinn/metode-kompetanse/issues/333
- [ ] https://github.com/Altinn/metode-kompetanse/issues/341
- [ ] https://github.com/Altinn/metode-kompetanse/issues/342
- [ ] https://github.com/Altinn/metode-kompetanse/issues/373
- [ ] https://github.com/Altinn/metode-kompetanse/issues/278
- [ ] https://github.com/Altinn/metode-kompetanse/issues/343
- [ ] https://github.com/Altinn/metode-kompetanse/issues/323
- [ ] https://github.com/Altinn/metode-kompetanse/issues/371
- [ ] https://github.com/Altinn/metode-kompetanse/issues/337
```

**Comment by borrehovstol** [comment]
Lukker denne da vi har ferdigstilt de sakene som skulle ferdigstilles, de andre sakene knyttet til denne issuen vil ikke bli jobbet med.
