### ISSUE TITLE
Vurdere og følge opp utredning om vi kan bruke MS Forms for å samle inn Testpersoner til Brukertest

### ISSUE THREAD

**Issue by hildemari** [Altinn/metode-kompetanse#416]
```[tasklist]
### Tasks
- [x] Jus: Hør med Benedicte evnt, sende ressursforespørsel, Avsjekk med jurister, lagring av personopplysninger
- [x] Teste ut MS Forms og samle input i Excel
- [x] Snakke med Sigurd ang. innkjøp av brukertestverktøyet "UX-signals". Det er i prosess og går sin gang.
- [x] Bidra med å lage personvernvurdering for brukerbasen. Utkast klart til gjennomgang.
- [x] Møte med Benedicte for gjennomgang av utkast til personvernvurdering den 24/8
- [x] innarbeide kommentarer fra Benedicte i personvernvurderingen
- [x] Oppdatere og sende samtykke-skjema til godkjenning hos Benedicte
- [x] Siste finpuss og møte med jus om personvernvurdering og samtykkeerklæring
- [x] Avsluttende møte med Anikken og Dorte 27.nov.
- [x] Endelig godkjenning fra Avd.dir
```
