### ISSUE TITLE
Dokumentere og markedsføre Brukerbasen

### ISSUE THREAD

**Issue by hildemari** [Altinn/metode-kompetanse#418]
```[tasklist]
### Tasks
- [x] Markedsføre: Anikken skal ha et lite innlegg på neste Altinn-kaffe
- [x] Markedsføre: Vi er i dialog med Trude på KOM, innlegg om Brukerbasen på intranettet
- [x] Markedsføre: Innlegg i sosiale media, møte med Trude 19/3.
- [x] Dokumentere: Det er lagt ut info om Brukerbasen på nyopprettet nettsamfunn "Viva Engage - Bruktesting"
```

**Comment by hildemari** [comment]
Stenger denne nå. Brukerbasen er nå markedsført på Altinn-kaffen og i Nyhetsbrevet som også er delt i Sosiale media. Vi har fått kjempebra respons, pr.nå har vi fått inn 75 personer i Brukerbasen.
