### ISSUE TITLE
OKR - workshop høsten 2023

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/metode-kompetanse#422]
[OKR_onboarding i team.docx](https://github.com/Altinn/metode-kompetanse/files/11879538/OKR_onboarding.i.team.docx)

Planlegging av arbeidet med OKR i BOD høsten 2023.

## Oppgaver
- [x] Sende ut innkalling til produkteiere (priortert liste, se vedlegget over) med foreslåtte datoer i september for WS i Oslo
- [x] Møte med Kim 31.8.23 - planlegging
- [x] Planlegge WS 
- [x] Møte med lederlaget 08.09.23
```[tasklist]
### Tasks
```

- [x] Avholdt workshop Oslo med sentrale team utvikling
- [x] Samlet tilbakemeldinger fra team
- [x] Scope videre arbeid - Dan Remi
- [x] Ledermøte fredag - forankre videre arbeid

```[tasklist]
### Tasks
```
