### ISSUE TITLE
Praktisk tilrettelegging for rekruttering ifbm brukertesting

### ISSUE THREAD

**Issue by hildemari** [Altinn/metode-kompetanse#431]
- [x] Finne ut av HR-kode/ lenke (Hilde)
- [x] Låse og passordbeskytte excelfil (Hilde)
- [x] ABS må få tekster og informasjon til rekruttering og e-post som skal sendes ut (Dorte og Anikken)
- [x] Få med brukerstøtte Leikanger (Dorte)
- [x] Felles oppstartsmøte med info til brukerstøttene, 9/1
- [x] Avklare med KOM Bruke sosiale media. Henge opp plakater i det offentlige osv... (Hilde)
- [x] Infomøter for ABS, den 18/1
- [x] Lage plakater og flyers som kan brukes på yrkesmessene m.m
- [x] Gikk oss på personvern-issues og måtte opprette nytt team i Teams. Fikk også laget nytt påmeldingsskjema og Excelfil  
- [x] Etterarbeid og oppsummering
- [x] Brukerbasen er i drift 

```[tasklist]
### Tasks
```
