### ISSUE TITLE
Kurs for OKR-ambassadører

### ISSUE THREAD

**Issue by arild-65** [Altinn/metode-kompetanse#450]
Team metode og kompetanse skal arrangere kurs for OKR ambassadører. Formålet med kurset er at avdelingen skal kunne drive OKR-prosessen uten hjelp fra eksterne. Det legges opp til digitalt kurs med 6 moduler.
```[tasklist]
### Tasks
- [x] Plukke ut deltakere
- [x] Modul 1 gjennomført
- [x] Modul 2/27. feb gjennomført
- [x] Modul 3/1. mars gjennomført
- [x] Modul 4/5. mars gjennomført
- [x] Modul 5/19. mars gjennomført
- [x] Modul 6/9. april gjennomført
```
